### ISSUE TITLE
{0} is not replaced with argument value

### ISSUE THREAD

**Issue by fedotxxl** [rodionmoiseev/c10n#36]
Hello. I configured C10N following way:

```
C10N.configure(new C10NConfigBase(){
            @Override
            public void configure(){
                install(new DefaultC10NAnnotations());
                setLocaleProvider(() -> Locale.ENGLISH);
            }
        });
```

and I've got following method:

```
@En("Can't load page by url {0}")
String pageNotLoaded(String url);
```

which returns `Can't load page by url {0}` instead of `Can't load page by url MY_CUSTOM_URL`

How can I fix it?

**Comment by rodionmoiseev** [comment]
Hi. One possible problem is that you're calling `C10N.get(...)` too early, before `C10N.configure(...)` had the chance to execute.

**Comment by fedotxxl** [comment]
Nope... Can you tell me class/method which replaces `{0}` values - I'll try to debug it

**Comment by rodionmoiseev** [comment]
[C10NInvokationHandler#invoke](https://github.com/rodionmoiseev/c10n/blob/1df6dab9700658b5b27463095ca090a28b178474/core/src/main/java/c10n/DefaultC10NMsgFactory.java#L319) get's invoked first. Then, [getStringValue](https://github.com/rodionmoiseev/c10n/blob/1df6dab9700658b5b27463095ca090a28b178474/core/src/main/java/c10n/DefaultC10NMsgFactory.java#L332) will do most heavy lifting of retrieving the string and formatting it.

**Comment by rodionmoiseev** [comment]
The above is for ver 1.1

**Comment by rodionmoiseev** [comment]
Hope this is not too urgent, because I have to go now. If you cannot resolve the issue, please post your full set-up and I will try to reproduce it locally. Thanks!

**Comment by fedotxxl** [comment]
It was `java.text.MessageFormat.format` issue - `Can't` should be replaced with `Can''t` - http://stackoverflow.com/questions/17569608/format-a-message-using-messageformat-format-in-java

**Comment by rodionmoiseev** [comment]
omg, that was a nasty one! Thanks! I should probably put it on a wiki somewhere.
