### ISSUE TITLE
Use ICU4J

### ISSUE THREAD

**Issue by lelmarir** [rodionmoiseev/c10n#38]
I'd like to propose to use com.ibm.icu.text.MessageFormat instead of java.text.MessageFormat.

http://www.stuartgunter.org/even-better-java-i18n-pluralisation-using-icu4j/

**Comment by rodionmoiseev** [comment]
Thank you for the feedback!

In c10n I have originally provided a way to customize the behaviour of `MessageFormat`, but it currently does not pass around the `Locale` object, which seems to be required to use ICU4J. I will consider extending it to cover for this case.

**Comment by rodionmoiseev** [comment]
It should be possible to integrate ICU4J to use with c10n. You can get an idea on how to implement your custom message formatter [here](https://github.com/rodionmoiseev/c10n/blob/master/core/src/test/java/com/github/rodionmoiseev/c10n/formatters/CustomMessageFormatterTest.java)

This feature is currently only available in the latest 1.3-SNAPSHOT version.
