### ISSUE TITLE
Add OSGi Support

### ISSUE THREAD

**Issue by amitjoy** [rodionmoiseev/c10n#39]

**Comment by rodionmoiseev** [comment]
Hi,

Could you please elaborate a little more, please? Is this related to #37?

**Comment by amitjoy** [comment]
Yes, you are right. It's related to #37 but I would love to have this library as an OSGi bundle.

**Comment by amitjoy** [comment]
Apart from it, it would be really helpful if you can provide c10n core as an OSGi bundle which also packages all the necessary libraries such as Guice and et al.

**Comment by rodionmoiseev** [comment]
Currently I have no plans to support OSGi, as J am not at all familiar with the technology and the use cases for it. If you feel strongly the support is required please propose a patch, thanks!
