### ISSUE TITLE
Configure file encoding of message bundles

### ISSUE THREAD

**Issue by dbenninger** [rodionmoiseev/c10n#41]
As I understand it, UTF-8 is currently hard-coded when reading the message bundles. Our message bundles are ISO-8859-1 and it would be nice if we could configure that somehow.

What do you think?

**Comment by rodionmoiseev** [comment]
Yeah, its hard coded. Seems like it will need a patch to work. There are other work arounds but they are quite complex.

I can think of two ways to do this:

1) Add a new signature for 'bindBundle' method, that accepts read-encoding of the bundle. Keep the old method, defaulting to UFT8.
2) Add a new 'setBundleEncoding' method. Calling this once would set the encoding for all bundles bound. Easier to use, but you will net be able to have mixed encodings.

1) sounds somewhat better to me. What do you think?

**Comment by rodionmoiseev** [comment]
Sorry, formatting issue: the third point is supposed to say '1) sounds somewhat better to me...'

**Comment by dbenninger** [comment]
Yes, I would prefer 1) as well...
